spring:
  datasource:
    url: jdbc:mysql:///stu1?serverTimezone=UTC
    username: root
    password: w123
    driver-class-name: com.mysql.cj.jdbc.Driver
dubbo:
  application:
    name: student_provider
  registry:
    address: zookeeper://192.168.126.128:2181
  protocol:
    name: dubbo
    port: -1
server:
  port: 8081
